on:
  push:
    tags:
      - "*"

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Build
        run: |
          npm i -g vsce
          vsce package
      - name: Upload VSIX to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/vscode-markdown-kroki/vscode-markdown-kroki/*.vsix
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
